import { EventItem } from "./types";

const now = Date.now();
const hour = 3600_000;

export const DEMO_EVENTS: EventItem[] = [
  {
    id: "e1",
    title: "Поход в горы",
    category: "sport",
    imageUrl: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1600&q=80",
    startsAt: now + 24 * hour,
    locationName: "Горы Ала-Тоо",
    distanceKm: 25.5,
    organizerName: "Aksuu Team",
    organizerRating: 4.9,
    capacity: 15,
    joined: 15,
    price: 0,
    waitlistEnabled: true,
  },
  {
    id: "e2",
    title: "Йога на рассвете",
    category: "health",
    imageUrl: "https://images.unsplash.com/photo-1518609878373-06d740f60d8b?auto=format&fit=crop&w=1600&q=80",
    startsAt: now + 8 * hour,
    locationName: "Парк Панфилова",
    distanceKm: 3.2,
    organizerName: "Dana",
    organizerRating: 4.7,
    capacity: 12,
    joined: 10,
    price: 200,
  },
  {
    id: "e3",
    title: "Выставка современного искусства",
    category: "culture",
    imageUrl: "https://images.unsplash.com/photo-1520697222865-7f3a0c3e99af?auto=format&fit=crop&w=1600&q=80",
    startsAt: now + 3 * 24 * hour,
    locationName: "Галерея “Artishok”",
    distanceKm: 5.3,
    organizerName: "Artishok",
    organizerRating: 4.6,
    capacity: 25,
    joined: 22,
    price: 500,
  },
  {
    id: "e4",
    title: "Живой концерт на крыше",
    category: "culture",
    imageUrl: "https://images.unsplash.com/photo-1511379938547-c1f69419868d?auto=format&fit=crop&w=1600&q=80",
    startsAt: now + 6 * 24 * hour,
    locationName: "Loft Space",
    distanceKm: 7.1,
    organizerName: "Loft Events",
    organizerRating: 4.3,
    capacity: 40,
    joined: 39,
    price: 800,
  },
  {
    id: "e5",
    title: "Кулинарный мастер-класс",
    category: "hobby",
    imageUrl: "https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?auto=format&fit=crop&w=1600&q=80",
    startsAt: now + 2 * 24 * hour,
    locationName: "Студия “Вкус”",
    distanceKm: 8.7,
    organizerName: "Chef Studio",
    organizerRating: 4.8,
    capacity: 12,
    joined: 12,
    price: 1200,
    waitlistEnabled: true,
  },
];